### ISSUE TITLE
Users connected to group cannot see freshly connected users without page refresh 

### ISSUE THREAD

**Issue by pavlass2** [pavlass2/Hades#11]
New ChathHub (SignalR) method implementation: 

Name of the method to call: ConnectClient 

Parameters: userId, groupName 

Description: Method sets client connection and pairs it with a groupName. When new user connects to this group, every connected client will be notified. 

Frontend usage: Call this method before calling SendMessage method to register client into the group. Only group members will receive notifications about new user connections and new messages. 

To receive the notification, subscribe to NewUserConnected. When new user connects to the group, other members will be notified using NewUserConnected. JSON body will contain UserName of the newly connected user. 

- [ ] Backend

- [x] Frontend

**Comment by pavlass2** [comment]
@Rosta6 Please implement the ConnectClient frontend call and NewUserConnected subscription, then test it.

**Comment by pavlass2** [comment]
@Rosta6 Please confirm the solution works and close this.

**Comment by Naty2942** [comment]
@pavlass2 Solution works. :)
