### ISSUE TITLE
User is not deleted after leaving a room

### ISSUE THREAD

**Issue by pavlass2** [pavlass2/Hades#7]
Every user has to be deleted after he clicks the Leave" button.

- [x] BACKEND: Implement DeleteUser method in GroupController, that calls DB and deletes all user data of the specified user.

- [x] FRONTEND: After user clicks "Leave" button, call GroupController with userId of the logged in user, then delete all personal data from web browser.

**Comment by pavlass2** [comment]
@Rosta6 
method: httpDelete
url: api/Group/DeleteUser
parameter: userId.

example:
`{
    "userId": "0380a5d3-510b-423b-89d6-5b712f20ecee"
}`

success response example:
`{
    "result": true,
    "resultText": "User successfully deleted."
}`

fail response example:
`{
    "result": false,
    "resultText": "Error occurred during deleting user. Please try again later. If the problem persists, please contact the web administration."
}`

You don't need to use the resultText, just make sure the user knows if it fails and then I guess do NOT delete his cookies. Otherwise he couldn't try again.

**Comment by Rosta6** [comment]
@pavlass2 
method: DELETE cannot contain variable inside the call as POST, only parameter in URL address after ? can be present.
Example:  ("https://localhost:5001/api/Group/DeleteUser?userId=97b95195-faa2-490a-8bb3-f970e4e9a2f4")

Solutions:
Option1: Using POST method.
Option2: Read URL variable.
