### ISSUE TITLE
List of Groups

### ISSUE THREAD

**Issue by Rosta6** [pavlass2/Hades#8]
Creating list of groups, where user is logged (only after browser close and open -> cookies are still active).
List will be presented at main screen in the bottom section. 

Backend - none
Frontend - add button for connection to active group for user after reopen browser (reading cookies)

**Comment by pavlass2** [comment]
If this is about one user being in multiple groups, than you should know that it is not currently possible. Joining any group at any moment creates new user.
Such feature would require backend implementation as well.
FYI @Rosta6

**Comment by Rosta6** [comment]
Nope. I have all info in the cookies. I will just redirect user to the group. No backend call needed. :)

**Comment by Rosta6** [comment]
Issue solved. User can find button on main page after reopen browser with last group. App verify all cookies and if all are still set, shows button in bottom part with name of active group.
