### ISSUE TITLE
Delete group not implemented

### ISSUE THREAD

**Issue by pavlass2** [pavlass2/Hades#9]
Until now, it was NOT possible to delete whole group at once but group founder should be able to do that. I see two possible ways of implementing this into UI.
1) For group founder: replace the "Leave" button with "Delete group" button.
2) For group founder: leave the same button but call "DeleteGroup" method instead. 
In both cases, founder should need to confirm this action either by clicking on "Yes" or possibly retyping the groupName correctly in "Are you sure? This will delete whole group and its data." dialog. Just to make sure users are not misclicking it since this action is not reversible.

New method details:
url: "api/Group/DeleteGroup";
type: httpdelete;
params: JsonElement with "groupName" value inside;

Request example:
`{
    "groupName": "test"
}`

Group deletion failed reply:
`{
    "result": false,
    "resultText": "Error occurred during deleting group. Please try again later. If the problem persists, please contact the web administration."
}`

Group deletion successful reply:
`{
    "result": true,
    "resultText": "Group and all of its members successfully deleted. Even Columbo wouldn't find anything now."
}`

- [x] Backend implementation
- [ ] Frontend implementation

**Comment by pavlass2** [comment]
Partially implemented. Students are currently not being deleted. ff9d3c2bef1a27d5fbbd5509502366fdbf87d4b4

**Comment by pavlass2** [comment]
Fully implemented. 22784528e61fc2c2b2708768a2fb5832bd476613

**Comment by Rosta6** [comment]
Bug: 
Deleting group returned success,
Creating new group with same name as deleted group return error: Group with this name already exists.

**Comment by Rosta6** [comment]
> Bug:
> Deleting group returned success,
> Creating new group with same name as deleted group return error: Group with this name already exists.

Not appearing again. Interesting.
